import uuid
from datetime import datetime
from typing import Optional, TYPE_CHECKING

from sqlalchemy import Float, ForeignKey, Index, Integer, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.questions import Question


class AIGenerationJob(Base):
    """Tracks each batch of questions generated by an AI model."""

    __tablename__ = "ai_generation_jobs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # openai | anthropic | gemini | local
    provider: Mapped[str] = mapped_column(Text, nullable=False)
    model: Mapped[str] = mapped_column(Text, nullable=False)
    prompt: Mapped[str] = mapped_column(Text, nullable=False)

    generated_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    accepted_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    rejected_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Estimated hallucination rate for this batch (0-1)
    hallucination_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        default=None, server_default=func.now(), nullable=False
    )
    # category_slug, language, difficulty_target, batch_id, cost_usd, tokens_used
    metadata_: Mapped[dict] = mapped_column(
        "metadata", JSONB, default=dict, server_default="{}", nullable=False
    )

    __table_args__ = (Index("ix_ai_generation_jobs_created_at", "created_at"),)


class AIReviewResult(Base):
    """Result of an AI model reviewing a question for quality/safety."""

    __tablename__ = "ai_review_results"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    question_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("questions.id", ondelete="CASCADE"),
        nullable=False,
    )
    model: Mapped[str] = mapped_column(Text, nullable=False)

    clarity_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ambiguity_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    kid_safety_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    factual_confidence_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    duplicate_probability: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # approve | reject | manual_review
    recommendation: Mapped[str] = mapped_column(Text, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        default=None, server_default=func.now(), nullable=False
    )
    # reasoning, reviewer_notes, similar_question_ids, etc.
    metadata_: Mapped[dict] = mapped_column(
        "metadata", JSONB, default=dict, server_default="{}", nullable=False
    )

    question: Mapped["Question"] = relationship(back_populates="ai_review_results")

    __table_args__ = (
        Index("ix_ai_review_results_question_id", "question_id"),
        Index("ix_ai_review_results_recommendation", "recommendation"),
    )
